# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk15

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

env:
  global:
    - CODECOV_TOKEN="b427a8d1-73e1-4cef-9823-5988abc7ed61"

# Отправлять уведомление на почт уyouremail@smtp.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      - onewaykd@gmail.com
    on_success: never # default: change
    on_failure: always # default: always